server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /predictive-application {
        try_files $uri /predictive-application/index.html;
    }

    location /predictive-application/assets/ {
        try_files $uri =404;
    }

    error_page 404 /predictive-application/index.html;
}